[cv]
name = "胡图图"
email = "tutuhu@gmail.com"
phone = "(+86) 820-820-8820"
website = "https://www.wikiwand.com/zh/大耳朵图图"
birthday = "2000.06.21"
# 路径
avatar = ""

[[educations]]
school = "翻斗幼儿园"
major = "软件工程"
degree = "幼儿园"
date = "2006.9 - now"

[[educations]]
school = "翻斗学前班"
major = "计算机科学与技术"
degree = "学前班"
date = "2003.9 - 2006.6"

[[projects]]
name = "翻斗幼儿园"
url = ""
date = "2014.6 - now"
desc = "开发工程师"
points = ["负责Kubernetes的网络部分", "负责Kubernetes的不知道什么部分"]

[[projects]]
name = "翻斗学前班"
url = ""
date = "2006.6 - 2022.6"
desc = "开发工程师"
points = [
    "负责Linux的文件系统部分，包括ext4, btrfs, xfs, f2fs",
    "负责Linux的网络部分，包括TCP/IP, UDP, SCTP, DCCP, IPv4, IPv6",
]

[[internships]]
company = "翻斗大街翻斗花园2号楼端茶倒水"
jobtitle = "项目负责人"
date = "2022.4 - 2022.6"
background = "在翻斗花园2号楼担任端茶倒水的工作，负责接待来访客人，保持环境整洁"

[[internships.duties]]
duty = "职责一：接待工作"
points = ["负责端茶倒水", "负责接待来访客人"]

[[internships.duties]]
duty = "职责二：环境维护"
points = ["负责浇花", "负责保持环境整洁"]

[internships.results]
results = ["服务质量提升", "个人荣誉", "环境改善"]
points = ["客人满意度提升30%", "获得月度优秀员工称号", "花园环境评分提升20%"]

[[internships]]
company = "翻斗幼儿园扮演小学生"
jobtitle = "项目负责人"
date = "2022.4 - 2022.6"
background = "在翻斗幼儿园体验小学生生活，与小朋友们一起学习、玩耍"

[[internships.duties]]
duty = "职责一：学习活动"
points = ["和张小帅一起玩", "和张小帅一起吃饭"]

[[internships.duties]]
duty = "职责二：生活起居"
points = ["和张小帅一起睡觉(误)"]

[internships.results]
results = ["学习成果", "活动表现", "社交能力"]
points = ["获得优秀学生称号", "在班级活动中表现突出", "成为班级最受欢迎的小朋友"]

[[awards]]
name = "最佳编导奖（获奖）"
date = "2006.11.8"

[[awards]]
name = "优秀长篇美术片奖（获奖）"
date = "2006.11.8"

[[awards]]
name = "中国电视艺术最高政府奖 - 星光奖"
date = "2010.1.24"

[[skills]]
name = "编程语言"
desc = "C/C++, Python, Java, JavaScript, HTML/CSS, PHP, SQL"

[[skills]]
name = "工具"
desc = "Git, Vim, VS Code, Linux, Docker, MySQL, MongoDB, Redis"

[[skills]]
name = "语言"
desc = "中文, 英语, 日语, 俄语, 法语, 德语, 西班牙语, 阿拉伯语, 葡萄牙语, 意大利语, 希腊语, 土耳其语"